// Utah Pollinator Habitat Plant Database
// 53 plants researched for Wasatch Front region
// Organized by Localscapes water zones and pollinator value

export interface Plant {
  id: string;
  commonName: string;
  scientificName: string;
  family: string;
  category: 'flower' | 'shrub' | 'tree' | 'groundcover' | 'grass' | 'succulent';
  utahNative: boolean;
  nativeRange?: string;
  
  // Visual
  icon: string;
  color: string;
  bloomColor: string;
  
  // Size
  heightMin: number;
  heightMax: number;
  widthMin: number;
  widthMax: number;
  spacing: number;
  growthRate: 'slow' | 'moderate' | 'fast';
  
  // Growing conditions
  sunNeeds: 'full' | 'partial' | 'shade' | 'full-partial' | 'partial-shade';
  waterNeeds: 'very-low' | 'low' | 'medium' | 'high';
  soilType: string[];
  droughtTolerant: boolean;
  saltTolerant: boolean;
  usdaZones: number[];
  elevationMin: number;
  elevationMax: number;
  
  // Bloom
  bloomMonths: number[];
  reblooms: boolean;
  
  // Pollinator value
  attractsPollinators: string[];
  specificPollinators: string[];
  nectarValue: number;
  pollenValue: number;
  hostPlant: string[] | null;
  
  // Water & maintenance
  gallonsPerWeek: number;
  wateringFrequency: string;
  localscapesZone: 0 | 1 | 2 | 3 | 4;
  maintenanceLevel: 'very-low' | 'low' | 'moderate' | 'high';
  deerResistant: boolean;
  rabbitResistant: boolean;
  
  // Landscape use
  landscapeUses: string[];
  goodForParkStrip: boolean;
  goodForSlopes: boolean;
  goodCompanions: string[];
  
  // Practical
  estimatedCost: number;
  availability: 'common' | 'moderate' | 'rare';
  utahNurseries: string[];
  notes?: string;
}

export const PLANTS: Plant[] = [
  // ============================================
  // PENSTEMON SPECIES (Utah has 100+ species)
  // ============================================
  {
    id: "rocky-mountain-penstemon",
    commonName: "Rocky Mountain Penstemon",
    scientificName: "Penstemon strictus",
    family: "Plantaginaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Southern Wyoming to northern Arizona, including Utah",
    icon: "💜",
    color: "#7C3AED",
    bloomColor: "blue-purple",
    heightMin: 1.5,
    heightMax: 2.5,
    widthMin: 2.5,
    widthMax: 3,
    spacing: 2.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["sandy", "rocky", "well-drained"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 6000,
    elevationMax: 11000,
    bloomMonths: [5, 6],
    reblooms: false,
    attractsPollinators: ["bees", "hummingbirds", "butterflies"],
    specificPollinators: ["bumblebees", "mason bees", "sweat bees"],
    nectarValue: 4,
    pollenValue: 4,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["rock gardens", "borders", "meadows", "pollinator gardens"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["sulfur-buckwheat", "blue-flax", "blanket-flower"],
    estimatedCost: 9,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Cache Valley Native Plants"]
  },
  {
    id: "firecracker-penstemon",
    commonName: "Firecracker Penstemon",
    scientificName: "Penstemon eatonii",
    family: "Plantaginaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Southwestern US including all of Utah",
    icon: "🔥",
    color: "#DC2626",
    bloomColor: "scarlet red",
    heightMin: 1.5,
    heightMax: 3,
    widthMin: 1.5,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["sandy", "gravelly", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 3000,
    elevationMax: 11000,
    bloomMonths: [4, 5, 6, 7],
    reblooms: true,
    attractsPollinators: ["hummingbirds", "bees"],
    specificPollinators: ["Broad-tailed Hummingbird", "Black-chinned Hummingbird", "Rufous Hummingbird"],
    nectarValue: 5,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "rarely",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["rock gardens", "xeriscape", "hummingbird gardens"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["apache-plume", "desert-marigold", "rabbitbrush"],
    estimatedCost: 10,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Native Utah Plants"]
  },
  {
    id: "palmers-penstemon",
    commonName: "Palmer's Penstemon",
    scientificName: "Penstemon palmeri",
    family: "Plantaginaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Southern Utah, Arizona, Nevada",
    icon: "🌸",
    color: "#F9A8D4",
    bloomColor: "light pink",
    heightMin: 4,
    heightMax: 6,
    widthMin: 2,
    widthMax: 3,
    spacing: 2,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["gravelly", "sandy", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8, 9],
    elevationMin: 3000,
    elevationMax: 8000,
    bloomMonths: [6, 7],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies", "hummingbirds"],
    specificPollinators: ["bumblebees - PRIMARY", "honeybees", "mason bees"],
    nectarValue: 5,
    pollenValue: 5,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "rarely",
    localscapesZone: 0,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["background", "borders", "meadows"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["desert-marigold", "globe-mallow", "rabbitbrush"],
    estimatedCost: 10,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "Cache Valley Native Plants"],
    notes: "FRAGRANT - one of few scented penstemons"
  },
  {
    id: "mat-penstemon",
    commonName: "Mat Penstemon",
    scientificName: "Penstemon caespitosus",
    family: "Plantaginaceae",
    category: "groundcover",
    utahNative: true,
    nativeRange: "Wyoming, Colorado, Utah, Arizona",
    icon: "💠",
    color: "#A78BFA",
    bloomColor: "lavender-purple",
    heightMin: 0.15,
    heightMax: 0.25,
    widthMin: 1,
    widthMax: 6,
    spacing: 1.5,
    growthRate: "slow",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["gravelly", "sandy", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 5000,
    elevationMax: 10500,
    bloomMonths: [6, 7],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Osmia brevis (specialist)", "small native bees"],
    nectarValue: 3,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "rarely",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["rock gardens", "groundcover", "between stepping stones"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["pussytoes", "stonecrop", "blue-grama"],
    estimatedCost: 12,
    availability: "moderate",
    utahNurseries: ["High Country Gardens", "Plant Select retailers"],
    notes: "Excellent lawn alternative groundcover"
  },
  {
    id: "wasatch-penstemon",
    commonName: "Wasatch Penstemon",
    scientificName: "Penstemon cyananthus",
    family: "Plantaginaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Utah Wasatch Mountains, Idaho, Montana, Wyoming",
    icon: "💙",
    color: "#3B82F6",
    bloomColor: "electric blue",
    heightMin: 1,
    heightMax: 3,
    widthMin: 1,
    widthMax: 1.5,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["sandy", "loam", "well-drained"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 4000,
    elevationMax: 9000,
    bloomMonths: [5, 6],
    reblooms: false,
    attractsPollinators: ["bees", "hummingbirds", "butterflies"],
    specificPollinators: ["bumblebees - favorite", "Broad-tailed Hummingbird"],
    nectarValue: 4,
    pollenValue: 4,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["borders", "rock gardens", "pollinator gardens"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["prairie-smoke", "blue-flax", "firecracker-penstemon"],
    estimatedCost: 8,
    availability: "common",
    utahNurseries: ["Cache Valley Native Plants", "Red Butte Garden"]
  },

  // ============================================
  // MILKWEEDS - Monarch Butterfly Hosts
  // ============================================
  {
    id: "showy-milkweed",
    commonName: "Showy Milkweed",
    scientificName: "Asclepias speciosa",
    family: "Apocynaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Throughout Utah at all elevations",
    icon: "🌸",
    color: "#EC4899",
    bloomColor: "pink",
    heightMin: 1.5,
    heightMax: 4,
    widthMin: 2,
    widthMax: 3,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["loam", "sand", "clay", "gravel"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [5, 6, 7, 8, 9],
    elevationMin: 2700,
    elevationMax: 8400,
    bloomMonths: [5, 6, 7],
    reblooms: false,
    attractsPollinators: ["butterflies", "bees", "hummingbirds", "moths"],
    specificPollinators: ["Monarch butterfly", "Queen butterfly", "bumblebees"],
    nectarValue: 5,
    pollenValue: 4,
    hostPlant: ["Monarch butterfly - OBLIGATE", "Queen butterfly", "Milkweed Tussock Moth"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["pollinator garden", "meadow", "butterfly garden"],
    goodForParkStrip: true,
    goodForSlopes: false,
    goodCompanions: ["purple-coneflower", "black-eyed-susan", "sulfur-buckwheat"],
    estimatedCost: 12,
    availability: "common",
    utahNurseries: ["Conservation Garden Park", "Great Basin Natives"],
    notes: "CRITICAL for western Monarch population. Spreads by rhizomes."
  },
  {
    id: "butterfly-weed",
    commonName: "Butterfly Weed",
    scientificName: "Asclepias tuberosa",
    family: "Apocynaceae",
    category: "flower",
    utahNative: false,
    nativeRange: "Eastern/southwestern US; southern Utah counties only",
    icon: "🧡",
    color: "#F97316",
    bloomColor: "orange",
    heightMin: 1,
    heightMax: 2.5,
    widthMin: 1.5,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "slow",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["sand", "gravel", "loam"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4500,
    elevationMax: 7500,
    bloomMonths: [6, 7, 8],
    reblooms: true,
    attractsPollinators: ["butterflies", "bees", "hummingbirds"],
    specificPollinators: ["Monarch butterfly", "Gray hairstreak", "swallowtails"],
    nectarValue: 5,
    pollenValue: 3,
    hostPlant: ["Monarch butterfly", "Queen butterfly"],
    gallonsPerWeek: 0,
    wateringFrequency: "rarely",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["pollinator garden", "xeriscape", "rock garden"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["blue-flax", "penstemon", "blanket-flower"],
    estimatedCost: 14,
    availability: "moderate",
    utahNurseries: ["Conservation Garden Park", "Millcreek Gardens"],
    notes: "Deep taproot - plant in permanent location. Does NOT spread."
  },
  {
    id: "narrowleaf-milkweed",
    commonName: "Narrowleaf Milkweed",
    scientificName: "Asclepias fascicularis",
    family: "Apocynaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Western US including Utah Great Basin",
    icon: "🤍",
    color: "#FDF2F8",
    bloomColor: "white-pink",
    heightMin: 1,
    heightMax: 3,
    widthMin: 1,
    widthMax: 3,
    spacing: 2,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["loam", "sand", "clay"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [5, 6, 7, 8, 9, 10],
    elevationMin: 3000,
    elevationMax: 7000,
    bloomMonths: [6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["butterflies", "bees", "beetles"],
    specificPollinators: ["Monarch - critical for western population", "Queen butterfly"],
    nectarValue: 5,
    pollenValue: 4,
    hostPlant: ["Monarch butterfly - OBLIGATE", "Queen butterfly"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["pollinator garden", "meadow", "cottage garden"],
    goodForParkStrip: true,
    goodForSlopes: false,
    goodCompanions: ["sulfur-buckwheat", "yarrow", "blue-flax"],
    estimatedCost: 12,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "High Country Gardens"],
    notes: "Longest bloom period of Utah milkweeds. Key for WESTERN monarchs."
  },

  // ============================================
  // AGASTACHE/HYSSOPS - Hummingbird Magnets
  // ============================================
  {
    id: "sunset-hyssop",
    commonName: "Sunset Hyssop",
    scientificName: "Agastache rupestris",
    family: "Lamiaceae",
    category: "flower",
    utahNative: false,
    nativeRange: "Arizona, New Mexico, northern Mexico",
    icon: "🧡",
    color: "#FB923C",
    bloomColor: "salmon-orange",
    heightMin: 1.5,
    heightMax: 3,
    widthMin: 1,
    widthMax: 1.5,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "gravelly"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [5, 6, 7, 8, 9],
    elevationMin: 4200,
    elevationMax: 7000,
    bloomMonths: [6, 7, 8, 9, 10],
    reblooms: true,
    attractsPollinators: ["hummingbirds", "butterflies", "bees", "moths"],
    specificPollinators: ["Black-chinned Hummingbird", "Broad-tailed Hummingbird", "Sphinx moths"],
    nectarValue: 5,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["borders", "rock gardens", "hummingbird gardens", "containers"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["lavender", "penstemon", "ornamental grasses"],
    estimatedCost: 15,
    availability: "common",
    utahNurseries: ["High Country Gardens", "Glover Nursery", "Millcreek Gardens"],
    notes: "Root beer/licorice fragrance. Very long bloom season."
  },
  {
    id: "hummingbird-mint",
    commonName: "Hummingbird Mint",
    scientificName: "Agastache cana",
    family: "Lamiaceae",
    category: "flower",
    utahNative: false,
    nativeRange: "New Mexico and western Texas mountains",
    icon: "💗",
    color: "#DB2777",
    bloomColor: "raspberry pink",
    heightMin: 2,
    heightMax: 3,
    widthMin: 1.5,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "gravelly"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [5, 6, 7, 8, 9],
    elevationMin: 4200,
    elevationMax: 7500,
    bloomMonths: [6, 7, 8, 9, 10],
    reblooms: true,
    attractsPollinators: ["hummingbirds", "butterflies", "bees"],
    specificPollinators: ["Broad-tailed Hummingbird - primary", "Black-chinned Hummingbird"],
    nectarValue: 5,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["borders", "rock gardens", "containers"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["sunset-hyssop", "lavender", "salvia"],
    estimatedCost: 15,
    availability: "moderate",
    utahNurseries: ["High Country Gardens", "specialty nurseries"],
    notes: "Bubblegum/mint fragrance"
  },
  {
    id: "blue-fortune-agastache",
    commonName: "Blue Fortune Agastache",
    scientificName: "Agastache 'Blue Fortune'",
    family: "Lamiaceae",
    category: "flower",
    utahNative: false,
    nativeRange: "Cultivated hybrid",
    icon: "💜",
    color: "#8B5CF6",
    bloomColor: "lavender-blue",
    heightMin: 2,
    heightMax: 3,
    widthMin: 1.5,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "average garden soil"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 7500,
    bloomMonths: [7, 8, 9, 10],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies", "hummingbirds"],
    specificPollinators: ["bumblebees - especially attracted", "swallowtails", "skippers"],
    nectarValue: 5,
    pollenValue: 4,
    hostPlant: null,
    gallonsPerWeek: 1,
    wateringFrequency: "weekly",
    localscapesZone: 2,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["borders", "mass plantings", "cut flowers"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["echinacea", "rudbeckia", "ornamental grasses"],
    estimatedCost: 12,
    availability: "common",
    utahNurseries: ["Glover Nursery", "Millcreek Gardens", "Home Depot"]
  },

  // ============================================
  // EARLY SPRING BLOOMERS - Critical Gap Fillers
  // ============================================
  {
    id: "pasque-flower",
    commonName: "Pasque Flower",
    scientificName: "Pulsatilla patens",
    family: "Ranunculaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Western North America from Alaska to Utah",
    icon: "💜",
    color: "#7C3AED",
    bloomColor: "blue-violet",
    heightMin: 0.33,
    heightMax: 1,
    widthMin: 0.5,
    widthMax: 1,
    spacing: 1,
    growthRate: "slow",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8],
    elevationMin: 330,
    elevationMax: 12500,
    bloomMonths: [3, 4, 5],
    reblooms: false,
    attractsPollinators: ["bees", "early flies"],
    specificPollinators: ["Queen bumblebees emerging from hibernation", "early mining bees"],
    nectarValue: 3,
    pollenValue: 4,
    hostPlant: null,
    gallonsPerWeek: 0.25,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["rock gardens", "alpine gardens", "naturalized areas"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["prairie-smoke", "wild-lupine"],
    estimatedCost: 12,
    availability: "rare",
    utahNurseries: ["Great Basin Natives", "specialty sales"],
    notes: "EARLIEST BLOOMER - emerges through snow in March!"
  },
  {
    id: "oregon-grape",
    commonName: "Creeping Oregon Grape",
    scientificName: "Mahonia repens",
    family: "Berberidaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Throughout Utah above 3,500 feet",
    icon: "🌼",
    color: "#FDE047",
    bloomColor: "bright yellow",
    heightMin: 0.5,
    heightMax: 2,
    widthMin: 1,
    widthMax: 3,
    spacing: 2.5,
    growthRate: "slow",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "loamy", "alkaline"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 3500,
    elevationMax: 10000,
    bloomMonths: [4, 5, 6],
    reblooms: false,
    attractsPollinators: ["bees", "hummingbirds", "butterflies"],
    specificPollinators: ["Queen bumblebees", "mason bees", "hummingbirds"],
    nectarValue: 4,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["groundcover", "dry shade", "erosion control"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["serviceberry", "golden-currant", "bigtooth-maple"],
    estimatedCost: 9,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Glover Nursery", "Conservation Garden Park"],
    notes: "EXCELLENT for dry shade. Evergreen. Blue berries for birds."
  },
  {
    id: "golden-banner",
    commonName: "Golden Banner",
    scientificName: "Thermopsis montana",
    family: "Fabaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Western US Rocky Mountains",
    icon: "💛",
    color: "#FACC15",
    bloomColor: "golden yellow",
    heightMin: 1.5,
    heightMax: 3,
    widthMin: 1.5,
    widthMax: 2,
    spacing: 2,
    growthRate: "moderate",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "rocky", "clay-tolerant"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 4000,
    elevationMax: 11500,
    bloomMonths: [5, 6, 7],
    reblooms: false,
    attractsPollinators: ["bumblebees", "native bees", "butterflies"],
    specificPollinators: ["Bombus appositus", "Bombus bifarius", "Bombus occidentalis"],
    nectarValue: 4,
    pollenValue: 4,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["meadow gardens", "prairie plantings", "slopes"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["lupines", "penstemons", "native grasses"],
    estimatedCost: 11,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "Granite Seed"],
    notes: "NITROGEN-FIXING legume. Toxic to livestock."
  },
  {
    id: "desert-parsley",
    commonName: "Desert Parsley / Biscuitroot",
    scientificName: "Lomatium dissectum",
    family: "Apiaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Utah high deserts and Wasatch foothills",
    icon: "🌿",
    color: "#A3E635",
    bloomColor: "yellow to purple",
    heightMin: 2,
    heightMax: 4,
    widthMin: 2,
    widthMax: 5,
    spacing: 3,
    growthRate: "slow",
    sunNeeds: "full-partial",
    waterNeeds: "very-low",
    soilType: ["well-drained", "rocky", "sandy", "gravelly"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 500,
    elevationMax: 10000,
    bloomMonths: [3, 4, 5],
    reblooms: false,
    attractsPollinators: ["native bees", "mining bees", "butterflies", "flies"],
    specificPollinators: ["21+ Andrena mining bee species", "Anise Swallowtail"],
    nectarValue: 5,
    pollenValue: 5,
    hostPlant: ["Anise Swallowtail - CONFIRMED"],
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["pollinator gardens", "butterfly gardens", "naturalized areas"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["sagebrush", "rabbitbrush", "penstemons"],
    estimatedCost: 16,
    availability: "rare",
    utahNurseries: ["Great Basin Natives", "specialty sales"],
    notes: "EARLIEST BLOOMER - flowers as early as MARCH! Swallowtail host."
  },
  {
    id: "golden-currant",
    commonName: "Golden Currant",
    scientificName: "Ribes aureum",
    family: "Grossulariaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Throughout western US including all of Utah",
    icon: "🌼",
    color: "#FCD34D",
    bloomColor: "golden yellow",
    heightMin: 6,
    heightMax: 10,
    widthMin: 6,
    widthMax: 10,
    spacing: 8,
    growthRate: "fast",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["adaptable", "clay", "loam", "sand"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [2, 3, 4, 5, 6, 7, 8],
    elevationMin: 3500,
    elevationMax: 9000,
    bloomMonths: [4, 5],
    reblooms: false,
    attractsPollinators: ["hummingbirds", "bumblebees", "butterflies"],
    specificPollinators: ["First food for migrating hummingbirds", "Queen bumblebees"],
    nectarValue: 5,
    pollenValue: 3,
    hostPlant: ["Cecropia moth"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: false,
    rabbitResistant: false,
    landscapeUses: ["hedge", "wildlife garden", "erosion control"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["serviceberry", "chokecherry", "woods-rose"],
    estimatedCost: 15,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Conservation Garden Park"],
    notes: "FIRST SHRUB TO BLOOM in spring. Strong clove scent. Edible berries."
  },

  // ============================================
  // LATE FALL BLOOMERS - Migration Support
  // ============================================
  {
    id: "maximilian-sunflower",
    commonName: "Maximilian Sunflower",
    scientificName: "Helianthus maximiliani",
    family: "Asteraceae",
    category: "flower",
    utahNative: false,
    nativeRange: "Central US prairies; naturalized in Utah",
    icon: "🌻",
    color: "#FDE047",
    bloomColor: "yellow",
    heightMin: 4,
    heightMax: 10,
    widthMin: 2,
    widthMax: 4,
    spacing: 3,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["adaptable", "clay", "loam", "sand"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 7500,
    bloomMonths: [8, 9, 10],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies", "birds"],
    specificPollinators: ["Monarch migration fuel", "50+ bird species eat seeds"],
    nectarValue: 4,
    pollenValue: 5,
    hostPlant: ["Silvery Checkerspot", "Painted Lady"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: false,
    landscapeUses: ["meadows", "backgrounds", "wildlife gardens", "screens"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["goldenrod", "asters", "native grasses"],
    estimatedCost: 10,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "High Country Gardens"],
    notes: "Blooms late into fall. Excellent bird food. Spreads by rhizomes."
  },
  {
    id: "aromatic-aster",
    commonName: "Aromatic Aster",
    scientificName: "Symphyotrichum oblongifolium",
    family: "Asteraceae",
    category: "flower",
    utahNative: false,
    nativeRange: "Central US; well-adapted to Utah",
    icon: "💜",
    color: "#A855F7",
    bloomColor: "lavender-purple",
    heightMin: 1,
    heightMax: 2,
    widthMin: 2,
    widthMax: 3,
    spacing: 2,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "rocky", "sandy", "clay"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 7500,
    bloomMonths: [9, 10, 11],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies", "moths"],
    specificPollinators: ["Migrating Monarchs", "late-season native bees"],
    nectarValue: 5,
    pollenValue: 4,
    hostPlant: ["Pearl Crescent", "Painted Lady"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["borders", "mass plantings", "meadows"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["goldenrod", "rabbitbrush", "ornamental grasses"],
    estimatedCost: 10,
    availability: "moderate",
    utahNurseries: ["High Country Gardens", "Glover Nursery"],
    notes: "LAST BLOOMER - continues after frost! Critical fall nectar."
  },
  {
    id: "rabbitbrush",
    commonName: "Rubber Rabbitbrush",
    scientificName: "Ericameria nauseosa",
    family: "Asteraceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Throughout Utah - very common",
    icon: "💛",
    color: "#EAB308",
    bloomColor: "golden yellow",
    heightMin: 2,
    heightMax: 5,
    widthMin: 2,
    widthMax: 4,
    spacing: 3,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["sandy", "rocky", "clay", "alkaline", "saline"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [4, 5, 6, 7, 8, 9],
    elevationMin: 3000,
    elevationMax: 10000,
    bloomMonths: [8, 9, 10],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies", "moths", "beetles"],
    specificPollinators: ["135+ pollinator species documented", "Rabbitbrush Beetle"],
    nectarValue: 5,
    pollenValue: 5,
    hostPlant: ["Northern Checkerspot", "Rabbitbrush Beetle"],
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["xeriscape", "restoration", "wildlife gardens"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["sagebrush", "penstemons", "native grasses"],
    estimatedCost: 8,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Granite Seed"],
    notes: "ONE OF MOST IMPORTANT late season nectar sources in Utah."
  },
  {
    id: "goldenrod",
    commonName: "Goldenrod",
    scientificName: "Solidago velutina",
    family: "Asteraceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Utah native species (threenerve goldenrod)",
    icon: "💛",
    color: "#FDE047",
    bloomColor: "golden yellow",
    heightMin: 1,
    heightMax: 5,
    widthMin: 1,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["adaptable", "loam", "clay", "sand"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 9500,
    bloomMonths: [8, 9, 10],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies", "beetles", "wasps"],
    specificPollinators: ["Monarch migration", "native bees - 50+ species"],
    nectarValue: 5,
    pollenValue: 5,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["meadows", "borders", "wildlife gardens"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["asters", "rabbitbrush", "native grasses"],
    estimatedCost: 9,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Granite Seed"],
    notes: "Does NOT cause allergies (ragweed does). Critical fall nectar."
  },

  // ============================================
  // NATIVE SHRUBS - Structure & Multi-Season Value
  // ============================================
  {
    id: "chokecherry",
    commonName: "Chokecherry",
    scientificName: "Prunus virginiana",
    family: "Rosaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Throughout Utah",
    icon: "🌸",
    color: "#FECACA",
    bloomColor: "white",
    heightMin: 6,
    heightMax: 20,
    widthMin: 6,
    widthMax: 15,
    spacing: 10,
    growthRate: "moderate",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["adaptable", "loam", "clay", "sand"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [2, 3, 4, 5, 6, 7, 8],
    elevationMin: 4000,
    elevationMax: 10000,
    bloomMonths: [4, 5],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies", "flies"],
    specificPollinators: ["Native bees", "mining bees", "syrphid flies"],
    nectarValue: 4,
    pollenValue: 4,
    hostPlant: ["456 Lepidoptera species - KEYSTONE!", "Two-tailed Swallowtail", "Western Tiger Swallowtail"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: false,
    rabbitResistant: false,
    landscapeUses: ["wildlife garden", "hedge", "screen", "naturalized area"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["serviceberry", "golden-currant", "woods-rose"],
    estimatedCost: 18,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Conservation Garden Park"],
    notes: "HIGHEST larval host value of any Utah shrub. Fruit toxic until fully ripe."
  },
  {
    id: "serviceberry",
    commonName: "Utah Serviceberry",
    scientificName: "Amelanchier utahensis",
    family: "Rosaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Utah endemic - throughout state",
    icon: "🌸",
    color: "#FFFFFF",
    bloomColor: "white",
    heightMin: 3,
    heightMax: 15,
    widthMin: 4,
    widthMax: 12,
    spacing: 8,
    growthRate: "moderate",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["well-drained", "rocky", "loam"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 3500,
    elevationMax: 10000,
    bloomMonths: [4, 5, 6],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Mason bees", "mining bees", "bumblebees"],
    nectarValue: 4,
    pollenValue: 4,
    hostPlant: ["Western Tiger Swallowtail", "Spring Azure", "Striped Hairstreak"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "very-low",
    deerResistant: false,
    rabbitResistant: false,
    landscapeUses: ["specimen", "hedge", "wildlife garden", "naturalized"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["chokecherry", "golden-currant", "oak"],
    estimatedCost: 25,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Conservation Garden Park"],
    notes: "Delicious edible berries. Excellent fall color."
  },
  {
    id: "apache-plume",
    commonName: "Apache Plume",
    scientificName: "Fallugia paradoxa",
    family: "Rosaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Southwestern US including southern Utah",
    icon: "🌸",
    color: "#FFFFFF",
    bloomColor: "white",
    heightMin: 3,
    heightMax: 5,
    widthMin: 3,
    widthMax: 5,
    spacing: 4,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["well-drained", "rocky", "sandy", "alkaline"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [5, 6, 7, 8, 9],
    elevationMin: 3000,
    elevationMax: 8000,
    bloomMonths: [4, 5, 6, 7, 8, 9, 10],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Native bees", "small butterflies"],
    nectarValue: 4,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["xeriscape", "erosion control", "foundation", "hedge"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["rabbitbrush", "desert-marigold", "penstemons"],
    estimatedCost: 12,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Conservation Garden Park"],
    notes: "LONGEST bloom season. Feathery pink seed plumes very ornamental."
  },
  {
    id: "cliffrose",
    commonName: "Cliffrose",
    scientificName: "Purshia stansburyana",
    family: "Rosaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Colorado Plateau including much of Utah",
    icon: "🌼",
    color: "#FFFBEB",
    bloomColor: "cream-yellow",
    heightMin: 6,
    heightMax: 25,
    widthMin: 6,
    widthMax: 15,
    spacing: 10,
    growthRate: "slow",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["well-drained", "rocky", "limestone", "alkaline"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 3500,
    elevationMax: 8000,
    bloomMonths: [4, 5, 6],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Native bees", "small butterflies"],
    nectarValue: 4,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: false,
    rabbitResistant: false,
    landscapeUses: ["xeriscape", "specimen", "wildlife garden"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["sagebrush", "rabbitbrush", "penstemons"],
    estimatedCost: 20,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives"],
    notes: "FRAGRANT flowers - like roses. Very long-lived. Evergreen."
  },
  {
    id: "fernbush",
    commonName: "Fernbush",
    scientificName: "Chamaebatiaria millefolium",
    family: "Rosaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Great Basin including Utah mountains",
    icon: "🌸",
    color: "#FFFFFF",
    bloomColor: "white",
    heightMin: 3,
    heightMax: 6,
    widthMin: 3,
    widthMax: 6,
    spacing: 5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["well-drained", "rocky", "sandy"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 5000,
    elevationMax: 10000,
    bloomMonths: [7, 8],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies", "beetles"],
    specificPollinators: ["Native bees", "small butterflies"],
    nectarValue: 4,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["xeriscape", "foundation", "specimen"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["penstemons", "rabbitbrush", "sagebrush"],
    estimatedCost: 18,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives"],
    notes: "Aromatic fern-like foliage. Blooms in PEAK summer when little else does."
  },
  {
    id: "woods-rose",
    commonName: "Woods' Rose",
    scientificName: "Rosa woodsii",
    family: "Rosaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Throughout western US including all of Utah",
    icon: "🌹",
    color: "#F472B6",
    bloomColor: "pink",
    heightMin: 2,
    heightMax: 6,
    widthMin: 3,
    widthMax: 6,
    spacing: 4,
    growthRate: "fast",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["adaptable", "loam", "clay", "sand"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8],
    elevationMin: 3500,
    elevationMax: 10000,
    bloomMonths: [5, 6, 7],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Native bees", "bumblebees", "rose specialists"],
    nectarValue: 4,
    pollenValue: 5,
    hostPlant: ["64 Lepidoptera species"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: false,
    rabbitResistant: false,
    landscapeUses: ["hedge", "wildlife garden", "erosion control"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["serviceberry", "chokecherry", "golden-currant"],
    estimatedCost: 12,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Conservation Garden Park"],
    notes: "Rose hips persist through winter - bird food. Spreads by suckers."
  },
  {
    id: "wax-currant",
    commonName: "Wax Currant",
    scientificName: "Ribes cereum",
    family: "Grossulariaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Throughout Utah mountains",
    icon: "🌸",
    color: "#FDF2F8",
    bloomColor: "white to pink",
    heightMin: 3,
    heightMax: 6,
    widthMin: 3,
    widthMax: 5,
    spacing: 4,
    growthRate: "moderate",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["well-drained", "rocky", "sandy"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 5000,
    elevationMax: 10000,
    bloomMonths: [4, 5, 6, 7],
    reblooms: false,
    attractsPollinators: ["bees", "hummingbirds"],
    specificPollinators: ["Native bees", "hummingbirds"],
    nectarValue: 4,
    pollenValue: 3,
    hostPlant: ["80+ Lepidoptera species"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["wildlife garden", "foundation", "hedge"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["serviceberry", "chokecherry", "oregon-grape"],
    estimatedCost: 15,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives"],
    notes: "Orange-red berries for birds. Good fall color."
  },
  {
    id: "four-wing-saltbush",
    commonName: "Four-wing Saltbush",
    scientificName: "Atriplex canescens",
    family: "Amaranthaceae",
    category: "shrub",
    utahNative: true,
    nativeRange: "Throughout Utah - very common in valleys",
    icon: "🌿",
    color: "#9CA3AF",
    bloomColor: "inconspicuous",
    heightMin: 3,
    heightMax: 6,
    widthMin: 4,
    widthMax: 8,
    spacing: 6,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["alkaline", "saline", "clay", "sand"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [4, 5, 6, 7, 8, 9, 10],
    elevationMin: 2500,
    elevationMax: 8000,
    bloomMonths: [6, 7],
    reblooms: false,
    attractsPollinators: ["butterflies"],
    specificPollinators: ["Painted Lady", "blues", "hairstreaks"],
    nectarValue: 1,
    pollenValue: 2,
    hostPlant: ["Pygmy Blue", "Western Pygmy Blue"],
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: false,
    rabbitResistant: false,
    landscapeUses: ["xeriscape", "restoration", "windbreak", "wildlife"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["rabbitbrush", "sagebrush", "indian-ricegrass"],
    estimatedCost: 8,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Granite Seed"],
    notes: "EXTREMELY salt tolerant. Four-winged seeds very ornamental."
  },

  // ============================================
  // GROUNDCOVERS - Lawn Alternatives
  // ============================================
  {
    id: "creeping-thyme",
    commonName: "Creeping Thyme",
    scientificName: "Thymus serpyllum",
    family: "Lamiaceae",
    category: "groundcover",
    utahNative: false,
    nativeRange: "European; well-adapted to Utah",
    icon: "💜",
    color: "#C084FC",
    bloomColor: "pink-purple",
    heightMin: 0.1,
    heightMax: 0.25,
    widthMin: 1,
    widthMax: 3,
    spacing: 1,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 8000,
    bloomMonths: [6, 7, 8],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Honeybees", "bumblebees", "small native bees"],
    nectarValue: 4,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["lawn alternative", "between pavers", "rock gardens"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["sedums", "penstemon", "lavender"],
    estimatedCost: 6,
    availability: "common",
    utahNurseries: ["any nursery"],
    notes: "Can tolerate light foot traffic. Aromatic when stepped on."
  },
  {
    id: "prairie-zinnia",
    commonName: "Prairie Zinnia",
    scientificName: "Zinnia grandiflora",
    family: "Asteraceae",
    category: "groundcover",
    utahNative: true,
    nativeRange: "Colorado Plateau including southern Utah",
    icon: "💛",
    color: "#FACC15",
    bloomColor: "yellow",
    heightMin: 0.3,
    heightMax: 0.7,
    widthMin: 1,
    widthMax: 2,
    spacing: 1,
    growthRate: "slow",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["well-drained", "rocky", "sandy", "alkaline"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8, 9],
    elevationMin: 3000,
    elevationMax: 7500,
    bloomMonths: [6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Native bees", "small butterflies", "skippers"],
    nectarValue: 3,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "rarely",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["groundcover", "rock gardens", "edges"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["blue-grama", "penstemons", "desert-marigold"],
    estimatedCost: 10,
    availability: "moderate",
    utahNurseries: ["High Country Gardens", "Great Basin Natives"],
    notes: "Paper-like flowers that persist. Spreads slowly."
  },
  {
    id: "pussytoes",
    commonName: "Pussytoes",
    scientificName: "Antennaria rosea",
    family: "Asteraceae",
    category: "groundcover",
    utahNative: true,
    nativeRange: "Throughout Utah mountains",
    icon: "🤍",
    color: "#FDF2F8",
    bloomColor: "pink-white",
    heightMin: 0.1,
    heightMax: 0.5,
    widthMin: 0.5,
    widthMax: 1.5,
    spacing: 0.75,
    growthRate: "slow",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["well-drained", "rocky", "sandy"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8],
    elevationMin: 4000,
    elevationMax: 12000,
    bloomMonths: [5, 6, 7],
    reblooms: false,
    attractsPollinators: ["butterflies", "small bees"],
    specificPollinators: ["American Lady butterfly - host", "Painted Lady"],
    nectarValue: 2,
    pollenValue: 2,
    hostPlant: ["American Lady butterfly", "Painted Lady"],
    gallonsPerWeek: 0.25,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["groundcover", "rock gardens", "between pavers"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["mat-penstemon", "sedums", "blue-grama"],
    estimatedCost: 8,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "High Country Gardens"],
    notes: "Silvery fuzzy leaves. Butterfly larval host!"
  },
  {
    id: "kinnikinnick",
    commonName: "Kinnikinnick / Bearberry",
    scientificName: "Arctostaphylos uva-ursi",
    family: "Ericaceae",
    category: "groundcover",
    utahNative: true,
    nativeRange: "Utah mountains",
    icon: "🌿",
    color: "#166534",
    bloomColor: "pink-white",
    heightMin: 0.25,
    heightMax: 0.5,
    widthMin: 3,
    widthMax: 6,
    spacing: 2,
    growthRate: "slow",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["well-drained", "acidic to neutral", "sandy"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [2, 3, 4, 5, 6, 7],
    elevationMin: 6000,
    elevationMax: 11000,
    bloomMonths: [4, 5, 6],
    reblooms: false,
    attractsPollinators: ["bees", "hummingbirds"],
    specificPollinators: ["Bumblebees", "native bees"],
    nectarValue: 3,
    pollenValue: 2,
    hostPlant: ["Brown Elfin butterfly", "Hoary Elfin"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["groundcover", "slopes", "erosion control"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["oregon-grape", "serviceberry"],
    estimatedCost: 14,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "specialty nurseries"],
    notes: "Evergreen. Red berries persist through winter. Prefers cooler sites."
  },

  // ============================================
  // NATIVE GRASSES - Skipper Habitat
  // ============================================
  {
    id: "blue-grama",
    commonName: "Blue Grama",
    scientificName: "Bouteloua gracilis",
    family: "Poaceae",
    category: "grass",
    utahNative: true,
    nativeRange: "Throughout Utah",
    icon: "🌾",
    color: "#84CC16",
    bloomColor: "purplish",
    heightMin: 0.5,
    heightMax: 1.5,
    widthMin: 0.5,
    widthMax: 1,
    spacing: 1,
    growthRate: "slow",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["well-drained", "sandy", "clay", "alkaline"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [3, 4, 5, 6, 7, 8, 9, 10],
    elevationMin: 3000,
    elevationMax: 8500,
    bloomMonths: [7, 8, 9],
    reblooms: false,
    attractsPollinators: ["butterflies"],
    specificPollinators: ["Skipper butterflies - host"],
    nectarValue: 0,
    pollenValue: 1,
    hostPlant: ["Green Skipper", "Garita Skipperling"],
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["lawn alternative", "meadow", "erosion control"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["prairie-zinnia", "penstemons", "desert-marigold"],
    estimatedCost: 6,
    availability: "common",
    utahNurseries: ["Granite Seed", "Great Basin Natives"],
    notes: "'Eyelash' seed heads very ornamental. True lawn alternative."
  },
  {
    id: "indian-ricegrass",
    commonName: "Indian Ricegrass",
    scientificName: "Achnatherum hymenoides",
    family: "Poaceae",
    category: "grass",
    utahNative: true,
    nativeRange: "Throughout Utah - UTAH STATE GRASS",
    icon: "🌾",
    color: "#A3E635",
    bloomColor: "airy panicles",
    heightMin: 1,
    heightMax: 2.5,
    widthMin: 1,
    widthMax: 1.5,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["sandy", "well-drained", "rocky"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [4, 5, 6, 7, 8, 9, 10],
    elevationMin: 2500,
    elevationMax: 9500,
    bloomMonths: [5, 6, 7],
    reblooms: false,
    attractsPollinators: ["butterflies"],
    specificPollinators: ["Skipper butterflies"],
    nectarValue: 0,
    pollenValue: 1,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["meadow", "xeriscape", "erosion control", "accent"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["rabbitbrush", "sagebrush", "penstemons"],
    estimatedCost: 6,
    availability: "common",
    utahNurseries: ["Granite Seed", "Great Basin Natives"],
    notes: "UTAH STATE GRASS. Seeds important for birds. Cool-season."
  },
  {
    id: "little-bluestem",
    commonName: "Little Bluestem",
    scientificName: "Schizachyrium scoparium",
    family: "Poaceae",
    category: "grass",
    utahNative: true,
    nativeRange: "Throughout much of North America including Utah",
    icon: "🌾",
    color: "#78350F",
    bloomColor: "bronze",
    heightMin: 2,
    heightMax: 4,
    widthMin: 1,
    widthMax: 2,
    spacing: 2,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "rocky", "clay"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 8000,
    bloomMonths: [8, 9],
    reblooms: false,
    attractsPollinators: ["butterflies"],
    specificPollinators: ["9+ skipper species - KEYSTONE grass"],
    nectarValue: 0,
    pollenValue: 1,
    hostPlant: ["Crossline Skipper", "Dotted Skipper", "Leonard's Skipper", "Ottoe Skipper", "plus 5 more"],
    gallonsPerWeek: 0.25,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["meadow", "prairie garden", "accent", "mass planting"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["asters", "goldenrod", "coneflowers"],
    estimatedCost: 8,
    availability: "common",
    utahNurseries: ["High Country Gardens", "Great Basin Natives"],
    notes: "EXCEPTIONAL copper-red fall color. Key skipper host."
  },
  {
    id: "sideoats-grama",
    commonName: "Sideoats Grama",
    scientificName: "Bouteloua curtipendula",
    family: "Poaceae",
    category: "grass",
    utahNative: true,
    nativeRange: "Throughout Utah",
    icon: "🌾",
    color: "#65A30D",
    bloomColor: "oat-like spikelets",
    heightMin: 1.5,
    heightMax: 3,
    widthMin: 1,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "rocky", "clay", "alkaline"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 8000,
    bloomMonths: [7, 8, 9],
    reblooms: false,
    attractsPollinators: ["butterflies"],
    specificPollinators: ["Dotted Skipper", "Leonard's Skipper", "Ottoe Skipper"],
    nectarValue: 0,
    pollenValue: 1,
    hostPlant: ["Multiple skipper species"],
    gallonsPerWeek: 0.25,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["meadow", "prairie garden", "erosion control"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["coneflowers", "asters", "penstemons"],
    estimatedCost: 7,
    availability: "common",
    utahNurseries: ["Granite Seed", "Great Basin Natives"],
    notes: "Distinctive one-sided seed heads. Warm-season grass."
  },

  // ============================================
  // KEY POLLINATOR FLOWERS
  // ============================================
  {
    id: "sulfur-buckwheat",
    commonName: "Sulfur Buckwheat",
    scientificName: "Eriogonum umbellatum",
    family: "Polygonaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Throughout Utah mountains and foothills",
    icon: "💛",
    color: "#FDE047",
    bloomColor: "sulfur yellow aging to rust",
    heightMin: 0.5,
    heightMax: 1.5,
    widthMin: 1,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "slow",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["well-drained", "rocky", "sandy", "gravelly"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 12000,
    bloomMonths: [6, 7, 8],
    reblooms: false,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["400+ pollinator species", "KEYSTONE plant"],
    nectarValue: 5,
    pollenValue: 5,
    hostPlant: ["37 Lepidoptera species", "Lupine Blue", "Mormon Metalmark"],
    gallonsPerWeek: 0,
    wateringFrequency: "none once established",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["rock gardens", "xeriscape", "meadows", "pollinator gardens"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["penstemons", "desert-marigold", "rabbitbrush"],
    estimatedCost: 10,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "High Country Gardens"],
    notes: "KEYSTONE PLANT - supports 400+ species. Dried flowers persist."
  },
  {
    id: "scarlet-globemallow",
    commonName: "Scarlet Globemallow",
    scientificName: "Sphaeralcea coccinea",
    family: "Malvaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Throughout Utah",
    icon: "🧡",
    color: "#EA580C",
    bloomColor: "orange-red",
    heightMin: 0.5,
    heightMax: 1.5,
    widthMin: 1,
    widthMax: 2,
    spacing: 1,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["sandy", "rocky", "clay", "alkaline"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [4, 5, 6, 7, 8, 9],
    elevationMin: 3500,
    elevationMax: 9000,
    bloomMonths: [5, 6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Globe Mallow Bees (Diadasia) - SPECIALIST", "only food source"],
    nectarValue: 4,
    pollenValue: 5,
    hostPlant: ["Painted Lady", "West Coast Lady", "Gray Hairstreak"],
    gallonsPerWeek: 0,
    wateringFrequency: "rarely",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["xeriscape", "rock gardens", "meadows", "park strips"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["penstemons", "rabbitbrush", "blue-grama"],
    estimatedCost: 8,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Conservation Garden Park"],
    notes: "Hosts SPECIALIST bees found nowhere else. Very long bloom."
  },
  {
    id: "desert-marigold",
    commonName: "Desert Marigold",
    scientificName: "Baileya multiradiata",
    family: "Asteraceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Southern Utah below 5,000 feet",
    icon: "🌼",
    color: "#FDE047",
    bloomColor: "bright yellow",
    heightMin: 1,
    heightMax: 1.5,
    widthMin: 1,
    widthMax: 1.5,
    spacing: 1,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["sandy", "rocky", "well-drained"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [7, 8, 9, 10],
    elevationMin: 2500,
    elevationMax: 5000,
    bloomMonths: [3, 4, 5, 6, 7, 8, 9, 10, 11],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Native bees", "small butterflies"],
    nectarValue: 4,
    pollenValue: 4,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "rarely",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["xeriscape", "rock gardens", "park strips"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["penstemons", "globe-mallow", "apache-plume"],
    estimatedCost: 8,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Conservation Garden Park"],
    notes: "LONGEST bloom season - March to November! Self-seeds."
  },
  {
    id: "blue-flax",
    commonName: "Blue Flax",
    scientificName: "Linum lewisii",
    family: "Linaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Throughout Utah",
    icon: "💙",
    color: "#60A5FA",
    bloomColor: "sky blue",
    heightMin: 1.5,
    heightMax: 2.5,
    widthMin: 1,
    widthMax: 1.5,
    spacing: 1,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 10000,
    bloomMonths: [5, 6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Native bees", "syrphid flies"],
    nectarValue: 3,
    pollenValue: 4,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["meadows", "borders", "pollinator gardens"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["penstemons", "blanket-flower", "yarrow"],
    estimatedCost: 6,
    availability: "common",
    utahNurseries: ["Great Basin Natives", "Granite Seed"],
    notes: "Flowers open in morning, drop by afternoon. Self-seeds freely."
  },
  {
    id: "blanket-flower",
    commonName: "Blanket Flower",
    scientificName: "Gaillardia aristata",
    family: "Asteraceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Northern Utah",
    icon: "🔥",
    color: "#DC2626",
    bloomColor: "red-yellow bicolor",
    heightMin: 2,
    heightMax: 3,
    widthMin: 1.5,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4500,
    elevationMax: 9000,
    bloomMonths: [6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Native bees", "Painted Lady", "skippers"],
    nectarValue: 5,
    pollenValue: 4,
    hostPlant: ["Bordered Patch butterfly"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["borders", "meadows", "pollinator gardens", "cut flowers"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["blue-flax", "penstemons", "coneflowers"],
    estimatedCost: 8,
    availability: "common",
    utahNurseries: ["any nursery"],
    notes: "Deadhead for continuous bloom. Very showy."
  },
  {
    id: "purple-coneflower",
    commonName: "Purple Coneflower",
    scientificName: "Echinacea purpurea",
    family: "Asteraceae",
    category: "flower",
    utahNative: false,
    nativeRange: "Eastern US; well-adapted to Utah",
    icon: "💜",
    color: "#9333EA",
    bloomColor: "purple-pink",
    heightMin: 2,
    heightMax: 4,
    widthMin: 1.5,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "loam", "clay"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 8000,
    bloomMonths: [6, 7, 8],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["6 specialist bee species", "swallowtails", "Painted Lady"],
    nectarValue: 5,
    pollenValue: 4,
    hostPlant: ["Silvery Checkerspot"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["borders", "mass plantings", "pollinator gardens"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["black-eyed-susan", "ornamental grasses", "agastache"],
    estimatedCost: 10,
    availability: "common",
    utahNurseries: ["any nursery"],
    notes: "Leave seed heads for goldfinches. Medicinal."
  },
  {
    id: "black-eyed-susan",
    commonName: "Black-eyed Susan",
    scientificName: "Rudbeckia hirta",
    family: "Asteraceae",
    category: "flower",
    utahNative: false,
    nativeRange: "Eastern North America; naturalized in Utah",
    icon: "🌻",
    color: "#FDE047",
    bloomColor: "yellow with black center",
    heightMin: 1,
    heightMax: 3,
    widthMin: 1,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "fast",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["adaptable", "loam", "clay", "sand"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 8000,
    bloomMonths: [6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies"],
    specificPollinators: ["Native bees", "swallowtails", "skippers"],
    nectarValue: 4,
    pollenValue: 5,
    hostPlant: ["Silvery Checkerspot", "Bordered Patch"],
    gallonsPerWeek: 1,
    wateringFrequency: "weekly",
    localscapesZone: 2,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: false,
    landscapeUses: ["borders", "meadows", "pollinator gardens", "cut flowers"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["purple-coneflower", "ornamental grasses", "asters"],
    estimatedCost: 6,
    availability: "common",
    utahNurseries: ["any nursery"],
    notes: "Biennial/short-lived perennial. Self-seeds readily."
  },
  {
    id: "wild-bergamot",
    commonName: "Wild Bergamot",
    scientificName: "Monarda fistulosa",
    family: "Lamiaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Northern Utah (nearly native statewide)",
    icon: "💜",
    color: "#A855F7",
    bloomColor: "lavender-pink",
    heightMin: 2,
    heightMax: 4,
    widthMin: 1.5,
    widthMax: 2,
    spacing: 2,
    growthRate: "moderate",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["adaptable", "loam", "clay", "sand"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4500,
    elevationMax: 9000,
    bloomMonths: [6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies", "hummingbirds", "moths"],
    specificPollinators: ["3 specialist bee species", "bumblebees", "Sphinx moths"],
    nectarValue: 5,
    pollenValue: 4,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["borders", "meadows", "pollinator gardens", "herb gardens"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["coneflowers", "black-eyed-susan", "native grasses"],
    estimatedCost: 10,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "High Country Gardens"],
    notes: "Better choice than Bee Balm (M. didyma) for Utah - more drought tolerant."
  },
  {
    id: "hummingbird-trumpet",
    commonName: "Hummingbird Trumpet",
    scientificName: "Epilobium canum",
    family: "Onagraceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Southwestern US including southern Utah",
    icon: "🔥",
    color: "#EF4444",
    bloomColor: "bright red-orange",
    heightMin: 1,
    heightMax: 2,
    widthMin: 2,
    widthMax: 3,
    spacing: 2,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "rocky", "sandy"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [5, 6, 7, 8, 9, 10],
    elevationMin: 4000,
    elevationMax: 8000,
    bloomMonths: [8, 9, 10],
    reblooms: true,
    attractsPollinators: ["hummingbirds"],
    specificPollinators: ["Hummingbirds - PRIMARY (evolved for them)", "Sphinx moths"],
    nectarValue: 5,
    pollenValue: 2,
    hostPlant: ["White-lined Sphinx moth"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["rock gardens", "hummingbird gardens", "slopes"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["rabbitbrush", "asters", "penstemons"],
    estimatedCost: 12,
    availability: "moderate",
    utahNurseries: ["High Country Gardens", "Great Basin Natives"],
    notes: "CRITICAL late-season hummingbird fuel before migration."
  },
  {
    id: "rocky-mountain-bee-plant",
    commonName: "Rocky Mountain Bee Plant",
    scientificName: "Cleome serrulata",
    family: "Cleomaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Throughout Utah",
    icon: "💗",
    color: "#EC4899",
    bloomColor: "pink to purple",
    heightMin: 2,
    heightMax: 5,
    widthMin: 2,
    widthMax: 3,
    spacing: 2,
    growthRate: "fast",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["adaptable", "sandy", "clay", "disturbed"],
    droughtTolerant: true,
    saltTolerant: true,
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
    elevationMin: 4000,
    elevationMax: 8500,
    bloomMonths: [6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["bees", "butterflies", "hummingbirds"],
    specificPollinators: ["Honeybees - excellent honey plant", "bumblebees"],
    nectarValue: 5,
    pollenValue: 5,
    hostPlant: ["Checkered White butterfly"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["meadows", "wildlife gardens", "pollinator gardens"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["sunflowers", "native grasses", "rabbitbrush"],
    estimatedCost: 5,
    availability: "common",
    utahNurseries: ["Granite Seed", "Great Basin Natives"],
    notes: "ANNUAL - must reseed each year. Excellent honey plant."
  },
  {
    id: "silvery-lupine",
    commonName: "Silvery Lupine",
    scientificName: "Lupinus argenteus",
    family: "Fabaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Throughout Utah mountains",
    icon: "💜",
    color: "#6366F1",
    bloomColor: "blue-purple",
    heightMin: 1,
    heightMax: 2.5,
    widthMin: 1,
    widthMax: 2,
    spacing: 1.5,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [4, 5, 6, 7, 8],
    elevationMin: 5000,
    elevationMax: 12000,
    bloomMonths: [5, 6, 7],
    reblooms: false,
    attractsPollinators: ["bumblebees", "butterflies"],
    specificPollinators: ["Bumblebees - primary", "Silvery Blue butterfly"],
    nectarValue: 4,
    pollenValue: 4,
    hostPlant: ["Silvery Blue", "Arrowhead Blue", "Lupine Blue"],
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["meadows", "slopes", "pollinator gardens"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["golden-banner", "penstemons", "native grasses"],
    estimatedCost: 10,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "Granite Seed"],
    notes: "NITROGEN-FIXING. Toxic to livestock. Blue butterfly host."
  },
  {
    id: "prairie-smoke",
    commonName: "Prairie Smoke",
    scientificName: "Geum triflorum",
    family: "Rosaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Utah mountains",
    icon: "🌸",
    color: "#FDA4AF",
    bloomColor: "pink nodding",
    heightMin: 0.5,
    heightMax: 1.5,
    widthMin: 1,
    widthMax: 1.5,
    spacing: 1,
    growthRate: "slow",
    sunNeeds: "full-partial",
    waterNeeds: "low",
    soilType: ["well-drained", "sandy", "rocky"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [3, 4, 5, 6, 7],
    elevationMin: 5000,
    elevationMax: 10000,
    bloomMonths: [4, 5, 6],
    reblooms: false,
    attractsPollinators: ["bees", "flies"],
    specificPollinators: ["Early bumblebees", "mining bees"],
    nectarValue: 3,
    pollenValue: 3,
    hostPlant: null,
    gallonsPerWeek: 0.5,
    wateringFrequency: "every 10-14 days",
    localscapesZone: 1,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["rock gardens", "alpine gardens", "borders"],
    goodForParkStrip: false,
    goodForSlopes: true,
    goodCompanions: ["pasque-flower", "penstemons", "native grasses"],
    estimatedCost: 12,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "High Country Gardens"],
    notes: "Feathery pink seed heads look like 'smoke'. Very ornamental."
  },
  {
    id: "desert-four-oclock",
    commonName: "Desert Four O'Clock",
    scientificName: "Mirabilis multiflora",
    family: "Nyctaginaceae",
    category: "flower",
    utahNative: true,
    nativeRange: "Southern Utah and Colorado Plateau",
    icon: "💜",
    color: "#A855F7",
    bloomColor: "magenta-purple",
    heightMin: 1,
    heightMax: 2,
    widthMin: 3,
    widthMax: 6,
    spacing: 4,
    growthRate: "moderate",
    sunNeeds: "full",
    waterNeeds: "very-low",
    soilType: ["sandy", "rocky", "well-drained"],
    droughtTolerant: true,
    saltTolerant: false,
    usdaZones: [5, 6, 7, 8, 9],
    elevationMin: 3000,
    elevationMax: 7500,
    bloomMonths: [5, 6, 7, 8, 9],
    reblooms: true,
    attractsPollinators: ["moths", "hummingbirds"],
    specificPollinators: ["Hawk moths (Sphinx moths) - PRIMARY", "White-lined Sphinx"],
    nectarValue: 5,
    pollenValue: 2,
    hostPlant: null,
    gallonsPerWeek: 0,
    wateringFrequency: "rarely",
    localscapesZone: 0,
    maintenanceLevel: "very-low",
    deerResistant: true,
    rabbitResistant: true,
    landscapeUses: ["xeriscape", "rock gardens", "naturalized areas"],
    goodForParkStrip: true,
    goodForSlopes: true,
    goodCompanions: ["penstemons", "rabbitbrush", "globe-mallow"],
    estimatedCost: 12,
    availability: "moderate",
    utahNurseries: ["Great Basin Natives", "High Country Gardens"],
    notes: "Opens late afternoon (4-8 PM). NIGHT-BLOOMING moth magnet."
  }
];

// ============================================
// HELPER FUNCTIONS
// ============================================

export function getPlantById(id: string): Plant | undefined {
  return PLANTS.find(p => p.id === id);
}

export function getPlantsByCategory(category: Plant['category']): Plant[] {
  return PLANTS.filter(p => p.category === category);
}

export function getPlantsByWaterZone(zone: 0 | 1 | 2 | 3 | 4): Plant[] {
  return PLANTS.filter(p => p.localscapesZone === zone);
}

export function getPlantsByBloomMonth(month: number): Plant[] {
  return PLANTS.filter(p => p.bloomMonths.includes(month));
}

export function getPlantsForPollinator(pollinator: string): Plant[] {
  return PLANTS.filter(p => 
    p.attractsPollinators.includes(pollinator) ||
    p.specificPollinators.some(sp => sp.toLowerCase().includes(pollinator.toLowerCase()))
  );
}

export function getHostPlants(): Plant[] {
  return PLANTS.filter(p => p.hostPlant && p.hostPlant.length > 0);
}

export function getNativePlants(): Plant[] {
  return PLANTS.filter(p => p.utahNative);
}

export function getEarlySpringBloomers(): Plant[] {
  return PLANTS.filter(p => p.bloomMonths.includes(3) || p.bloomMonths.includes(4));
}

export function getLateFallBloomers(): Plant[] {
  return PLANTS.filter(p => p.bloomMonths.includes(10) || p.bloomMonths.includes(11));
}

export function getLowestWaterPlants(): Plant[] {
  return PLANTS.filter(p => p.localscapesZone === 0);
}

export function getCompanions(plantId: string): Plant[] {
  const plant = getPlantById(plantId);
  if (!plant) return [];
  return plant.goodCompanions
    .map(id => getPlantById(id))
    .filter((p): p is Plant => p !== undefined);
}

export function calculateHabitatScore(plantIds: string[]): number {
  const plants = plantIds.map(id => getPlantById(id)).filter((p): p is Plant => p !== undefined);
  if (plants.length === 0) return 0;
  
  let score = 0;
  
  // Native plant bonus
  const nativeRatio = plants.filter(p => p.utahNative).length / plants.length;
  score += nativeRatio * 25;
  
  // Nectar/pollen value
  const avgNectar = plants.reduce((sum, p) => sum + p.nectarValue, 0) / plants.length;
  const avgPollen = plants.reduce((sum, p) => sum + p.pollenValue, 0) / plants.length;
  score += ((avgNectar + avgPollen) / 2) * 10;
  
  // Bloom coverage (months covered)
  const monthsCovered = new Set(plants.flatMap(p => p.bloomMonths)).size;
  score += (monthsCovered / 12) * 20;
  
  // Host plant bonus
  const hostPlants = plants.filter(p => p.hostPlant && p.hostPlant.length > 0).length;
  score += Math.min(hostPlants * 5, 15);
  
  // Water efficiency bonus
  const avgWaterZone = plants.reduce((sum, p) => sum + p.localscapesZone, 0) / plants.length;
  score += (4 - avgWaterZone) * 5;
  
  return Math.round(Math.min(score, 100));
}

// Export plant count for reference
export const PLANT_COUNT = PLANTS.length;
