// Central plant database - single source of truth
export interface Plant {
  id: string;
  commonName: string;
  scientificName: string;
  category: 'flower' | 'shrub' | 'groundcover' | 'tree';
  // Visual
  icon: string;
  color: string;
  // Size (feet)
  width: number;
  height: number;
  spacing: number;
  // Growing conditions
  sunNeeds: 'full' | 'partial' | 'shade';
  waterNeeds: 'low' | 'medium' | 'high';
  soilType: string[];
  // Bloom info
  bloomMonths: number[]; // 1-12
  bloomColor: string;
  // Pollinators
  attractsPollinators: ('bee' | 'butterfly' | 'hummingbird' | 'moth')[];
  nectarValue: 1 | 2 | 3; // 1=low, 3=high
  pollenValue: 1 | 2 | 3;
  // Water/irrigation
  gallonsPerWeek: number;
  wateringFrequency: string;
  wateringNotes: string;
  // Companion planting
  goodCompanions: string[];
  badCompanions: string[];
  // Pricing
  estimatedCost: { small: number; gallon: number; fiveGallon: number };
  // Utah specific
  utahNative: boolean;
  elevationRange: [number, number]; // feet
  usdaZones: number[];
}

export const PLANTS: Plant[] = [
  {
    id: 'desert-marigold',
    commonName: 'Desert Marigold',
    scientificName: 'Baileya multiradiata',
    category: 'flower',
    icon: '🌼',
    color: '#fbbf24',
    width: 1.5,
    height: 1,
    spacing: 1.5,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['sandy', 'well-drained'],
    bloomMonths: [3, 4, 5, 6, 7, 8, 9, 10, 11],
    bloomColor: 'yellow',
    attractsPollinators: ['bee', 'butterfly'],
    nectarValue: 3,
    pollenValue: 2,
    gallonsPerWeek: 0.5,
    wateringFrequency: 'Every 10-14 days',
    wateringNotes: 'Drought tolerant once established',
    goodCompanions: ['Blue Flax', 'Penstemon', 'Rabbitbrush'],
    badCompanions: [],
    estimatedCost: { small: 5, gallon: 12, fiveGallon: 35 },
    utahNative: true,
    elevationRange: [2500, 6500],
    usdaZones: [5, 6, 7, 8, 9],
  },
  {
    id: 'blue-flax',
    commonName: 'Blue Flax',
    scientificName: 'Linum lewisii',
    category: 'flower',
    icon: '💙',
    color: '#3b82f6',
    width: 1,
    height: 1.5,
    spacing: 1,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['any', 'well-drained'],
    bloomMonths: [5, 6, 7],
    bloomColor: 'blue',
    attractsPollinators: ['bee', 'butterfly'],
    nectarValue: 2,
    pollenValue: 3,
    gallonsPerWeek: 0.5,
    wateringFrequency: 'Every 10-14 days',
    wateringNotes: 'Very drought tolerant',
    goodCompanions: ['Desert Marigold', 'Penstemon', 'Blanket Flower'],
    badCompanions: [],
    estimatedCost: { small: 4, gallon: 10, fiveGallon: 28 },
    utahNative: true,
    elevationRange: [4000, 9000],
    usdaZones: [4, 5, 6, 7, 8],
  },
  {
    id: 'penstemon',
    commonName: 'Penstemon',
    scientificName: 'Penstemon spp.',
    category: 'flower',
    icon: '🌺',
    color: '#ec4899',
    width: 1.5,
    height: 2,
    spacing: 1.5,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['sandy', 'rocky', 'well-drained'],
    bloomMonths: [5, 6, 7],
    bloomColor: 'pink/purple',
    attractsPollinators: ['hummingbird', 'bee', 'butterfly'],
    nectarValue: 3,
    pollenValue: 2,
    gallonsPerWeek: 1,
    wateringFrequency: 'Weekly',
    wateringNotes: 'Moderate water, good drainage essential',
    goodCompanions: ['Blue Flax', 'Rabbitbrush', 'Apache Plume'],
    badCompanions: [],
    estimatedCost: { small: 6, gallon: 14, fiveGallon: 40 },
    utahNative: true,
    elevationRange: [4000, 10000],
    usdaZones: [4, 5, 6, 7, 8],
  },
  {
    id: 'blanket-flower',
    commonName: 'Blanket Flower',
    scientificName: 'Gaillardia aristata',
    category: 'flower',
    icon: '🔴',
    color: '#ef4444',
    width: 1.5,
    height: 1.5,
    spacing: 1,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['any', 'poor-ok'],
    bloomMonths: [6, 7, 8, 9],
    bloomColor: 'red/yellow',
    attractsPollinators: ['butterfly', 'bee'],
    nectarValue: 3,
    pollenValue: 2,
    gallonsPerWeek: 0.5,
    wateringFrequency: 'Every 10-14 days',
    wateringNotes: 'Thrives on neglect',
    goodCompanions: ['Blue Flax', 'Coneflower', 'Black-eyed Susan'],
    badCompanions: [],
    estimatedCost: { small: 5, gallon: 12, fiveGallon: 32 },
    utahNative: true,
    elevationRange: [4000, 8000],
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
  },
  {
    id: 'black-eyed-susan',
    commonName: 'Black-eyed Susan',
    scientificName: 'Rudbeckia hirta',
    category: 'flower',
    icon: '🌻',
    color: '#f59e0b',
    width: 2,
    height: 2,
    spacing: 1.5,
    sunNeeds: 'full',
    waterNeeds: 'medium',
    soilType: ['any'],
    bloomMonths: [6, 7, 8, 9, 10],
    bloomColor: 'yellow',
    attractsPollinators: ['butterfly', 'bee'],
    nectarValue: 3,
    pollenValue: 3,
    gallonsPerWeek: 1.5,
    wateringFrequency: 'Twice weekly',
    wateringNotes: 'Moderate water needs',
    goodCompanions: ['Coneflower', 'Blanket Flower', 'Bee Balm'],
    badCompanions: [],
    estimatedCost: { small: 5, gallon: 11, fiveGallon: 30 },
    utahNative: false, // Native to eastern US but adapted
    elevationRange: [4000, 7500],
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
  },
  {
    id: 'purple-coneflower',
    commonName: 'Purple Coneflower',
    scientificName: 'Echinacea purpurea',
    category: 'flower',
    icon: '💜',
    color: '#a855f7',
    width: 2,
    height: 3,
    spacing: 1.5,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['any', 'well-drained'],
    bloomMonths: [6, 7, 8],
    bloomColor: 'purple',
    attractsPollinators: ['butterfly', 'bee'],
    nectarValue: 3,
    pollenValue: 3,
    gallonsPerWeek: 1,
    wateringFrequency: 'Weekly',
    wateringNotes: 'Drought tolerant once established',
    goodCompanions: ['Black-eyed Susan', 'Bee Balm', 'Goldenrod'],
    badCompanions: [],
    estimatedCost: { small: 6, gallon: 14, fiveGallon: 38 },
    utahNative: false,
    elevationRange: [4000, 7000],
    usdaZones: [3, 4, 5, 6, 7, 8],
  },
  {
    id: 'bee-balm',
    commonName: 'Bee Balm',
    scientificName: 'Monarda didyma',
    category: 'flower',
    icon: '🔮',
    color: '#dc2626',
    width: 2,
    height: 3,
    spacing: 2,
    sunNeeds: 'full',
    waterNeeds: 'medium',
    soilType: ['rich', 'moist'],
    bloomMonths: [7, 8, 9],
    bloomColor: 'red',
    attractsPollinators: ['hummingbird', 'bee', 'butterfly'],
    nectarValue: 3,
    pollenValue: 2,
    gallonsPerWeek: 2,
    wateringFrequency: 'Twice weekly',
    wateringNotes: 'Prefers consistent moisture',
    goodCompanions: ['Coneflower', 'Black-eyed Susan'],
    badCompanions: [],
    estimatedCost: { small: 7, gallon: 15, fiveGallon: 42 },
    utahNative: false,
    elevationRange: [4000, 7000],
    usdaZones: [4, 5, 6, 7, 8, 9],
  },
  {
    id: 'goldenrod',
    commonName: 'Goldenrod',
    scientificName: 'Solidago spp.',
    category: 'flower',
    icon: '💛',
    color: '#eab308',
    width: 2,
    height: 3,
    spacing: 2,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['any'],
    bloomMonths: [8, 9, 10],
    bloomColor: 'yellow',
    attractsPollinators: ['bee', 'butterfly', 'moth'],
    nectarValue: 3,
    pollenValue: 3,
    gallonsPerWeek: 0.5,
    wateringFrequency: 'Every 10-14 days',
    wateringNotes: 'Very drought tolerant',
    goodCompanions: ['Coneflower', 'Aster'],
    badCompanions: [],
    estimatedCost: { small: 5, gallon: 12, fiveGallon: 30 },
    utahNative: true,
    elevationRange: [4000, 9000],
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
  },
  {
    id: 'rabbitbrush',
    commonName: 'Rabbitbrush',
    scientificName: 'Ericameria nauseosa',
    category: 'shrub',
    icon: '🌿',
    color: '#84cc16',
    width: 4,
    height: 4,
    spacing: 4,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['any', 'poor-ok'],
    bloomMonths: [8, 9, 10],
    bloomColor: 'yellow',
    attractsPollinators: ['bee', 'butterfly', 'moth'],
    nectarValue: 3,
    pollenValue: 3,
    gallonsPerWeek: 0.25,
    wateringFrequency: 'Monthly once established',
    wateringNotes: 'Extremely drought tolerant',
    goodCompanions: ['Desert Marigold', 'Penstemon', 'Apache Plume'],
    badCompanions: [],
    estimatedCost: { small: 8, gallon: 18, fiveGallon: 50 },
    utahNative: true,
    elevationRange: [3000, 9000],
    usdaZones: [4, 5, 6, 7, 8],
  },
  {
    id: 'apache-plume',
    commonName: 'Apache Plume',
    scientificName: 'Fallugia paradoxa',
    category: 'shrub',
    icon: '🤍',
    color: '#f5f5f4',
    width: 4,
    height: 5,
    spacing: 4,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['rocky', 'well-drained'],
    bloomMonths: [5, 6, 7, 8, 9, 10],
    bloomColor: 'white',
    attractsPollinators: ['bee', 'butterfly'],
    nectarValue: 2,
    pollenValue: 2,
    gallonsPerWeek: 0.5,
    wateringFrequency: 'Every 2 weeks',
    wateringNotes: 'Low water once established',
    goodCompanions: ['Rabbitbrush', 'Penstemon'],
    badCompanions: [],
    estimatedCost: { small: 10, gallon: 22, fiveGallon: 55 },
    utahNative: true,
    elevationRange: [3500, 7500],
    usdaZones: [4, 5, 6, 7, 8],
  },
  {
    id: 'creeping-thyme',
    commonName: 'Creeping Thyme',
    scientificName: 'Thymus serpyllum',
    category: 'groundcover',
    icon: '🌱',
    color: '#86efac',
    width: 1,
    height: 0.25,
    spacing: 1,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['any', 'well-drained'],
    bloomMonths: [6, 7],
    bloomColor: 'pink/purple',
    attractsPollinators: ['bee'],
    nectarValue: 2,
    pollenValue: 2,
    gallonsPerWeek: 0.5,
    wateringFrequency: 'Weekly',
    wateringNotes: 'Low water groundcover',
    goodCompanions: ['Sedum'],
    badCompanions: [],
    estimatedCost: { small: 4, gallon: 10, fiveGallon: 25 },
    utahNative: false,
    elevationRange: [4000, 8000],
    usdaZones: [4, 5, 6, 7, 8, 9],
  },
  {
    id: 'sedum',
    commonName: 'Sedum',
    scientificName: 'Sedum spp.',
    category: 'groundcover',
    icon: '🪴',
    color: '#22c55e',
    width: 1.5,
    height: 0.5,
    spacing: 1,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['any', 'poor-ok'],
    bloomMonths: [8, 9],
    bloomColor: 'pink/yellow',
    attractsPollinators: ['bee', 'butterfly'],
    nectarValue: 2,
    pollenValue: 1,
    gallonsPerWeek: 0.25,
    wateringFrequency: 'Every 2 weeks',
    wateringNotes: 'Succulent, very low water',
    goodCompanions: ['Creeping Thyme'],
    badCompanions: [],
    estimatedCost: { small: 4, gallon: 9, fiveGallon: 22 },
    utahNative: false,
    elevationRange: [4000, 8000],
    usdaZones: [3, 4, 5, 6, 7, 8, 9],
  },
  {
    id: 'desert-willow',
    commonName: 'Desert Willow',
    scientificName: 'Chilopsis linearis',
    category: 'tree',
    icon: '🌳',
    color: '#16a34a',
    width: 15,
    height: 25,
    spacing: 15,
    sunNeeds: 'full',
    waterNeeds: 'low',
    soilType: ['any', 'well-drained'],
    bloomMonths: [5, 6, 7, 8, 9],
    bloomColor: 'pink/purple',
    attractsPollinators: ['hummingbird', 'bee'],
    nectarValue: 3,
    pollenValue: 2,
    gallonsPerWeek: 2,
    wateringFrequency: 'Weekly deep soak',
    wateringNotes: 'Deep watering encourages deep roots',
    goodCompanions: [],
    badCompanions: [],
    estimatedCost: { small: 25, gallon: 45, fiveGallon: 95 },
    utahNative: false, // Southwest native, adapted to Utah
    elevationRange: [3000, 5500],
    usdaZones: [6, 7, 8, 9],
  },
  {
    id: 'serviceberry',
    commonName: 'Serviceberry',
    scientificName: 'Amelanchier alnifolia',
    category: 'tree',
    icon: '🌳',
    color: '#15803d',
    width: 12,
    height: 15,
    spacing: 10,
    sunNeeds: 'partial',
    waterNeeds: 'medium',
    soilType: ['any'],
    bloomMonths: [4, 5],
    bloomColor: 'white',
    attractsPollinators: ['bee', 'butterfly'],
    nectarValue: 2,
    pollenValue: 3,
    gallonsPerWeek: 2,
    wateringFrequency: 'Weekly',
    wateringNotes: 'Moderate water',
    goodCompanions: [],
    badCompanions: [],
    estimatedCost: { small: 30, gallon: 55, fiveGallon: 120 },
    utahNative: true,
    elevationRange: [5000, 9000],
    usdaZones: [2, 3, 4, 5, 6, 7],
  },
];

// Helper functions
export const getPlantById = (id: string) => PLANTS.find(p => p.id === id);
export const getPlantByName = (name: string) => PLANTS.find(p => p.commonName === name);
export const getPlantsByCategory = (category: Plant['category']) => PLANTS.filter(p => p.category === category);
export const getPlantsForPollinator = (pollinator: 'bee' | 'butterfly' | 'hummingbird' | 'moth') => 
  PLANTS.filter(p => p.attractsPollinators.includes(pollinator));
export const getBloomingPlants = (month: number) => PLANTS.filter(p => p.bloomMonths.includes(month));
export const getCompanions = (plantId: string) => {
  const plant = getPlantById(plantId);
  return plant?.goodCompanions.map(name => getPlantByName(name)).filter(Boolean) || [];
};
